name: GitHub Actions
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: client
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: server
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./
          start: "npm run prod --prefix server, npm run start --prefix client"
          wait-on: "http://localhost:8080, http://localhost:8081/songs"
          project: ./client
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
