name: GitHub Actions
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: client
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: server
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./
          start: "npm run prod --prefix server, npm run start --prefix client"
          wait-on: "http://localhost:8080"
          project: ./client
          record: true
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |
            client/cypress/videos
